package repository

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/modules/mongodb"
	"github.com/testcontainers/testcontainers-go/wait"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"event/internal/models"
)

type EventRepositoryIntegrationTestSuite struct {
	suite.Suite
	container  testcontainers.Container
	client     *mongo.Client
	repository EventRepository
	ctx        context.Context
}

func (suite *EventRepositoryIntegrationTestSuite) SetupSuite() {
	var err error
	suite.ctx = context.Background()

	// Create MongoDB container
	suite.container, err = mongodb.Run(suite.ctx, "mongo:7",
		mongodb.WithUsername("testuser"),
		mongodb.WithPassword("testpass"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("Waiting for connections").
				WithOccurrence(1).
				WithStartupTimeout(60*time.Second),
		),
	)
	suite.Require().NoError(err)

	// Get connection string
	uri, err := suite.container.Endpoint(suite.ctx, "")
	suite.Require().NoError(err)

	// Format as MongoDB URI with authentication
	mongoURI := "mongodb://testuser:testpass@" + uri

	// Connect to MongoDB
	suite.client, err = mongo.Connect(suite.ctx, options.Client().ApplyURI(mongoURI))
	suite.Require().NoError(err)

	// Test connection
	err = suite.client.Ping(suite.ctx, nil)
	suite.Require().NoError(err)

	suite.repository = NewMongoEventRepository(suite.client, "test_db")
}

func (suite *EventRepositoryIntegrationTestSuite) TearDownSuite() {
	if suite.client != nil {
		suite.client.Disconnect(suite.ctx)
	}
	if suite.container != nil {
		suite.container.Terminate(suite.ctx)
	}
}

func (suite *EventRepositoryIntegrationTestSuite) SetupTest() {
	// Clean up the database before each test
	database := suite.client.Database("test_db")
	collections, err := database.ListCollectionNames(suite.ctx, nil)
	suite.Require().NoError(err)

	for _, collection := range collections {
		err := database.Collection(collection).Drop(suite.ctx)
		suite.Require().NoError(err)
	}
}

// testEvent creates a test event for integration tests
func testEvent() *models.Event {
	brandID := primitive.NewObjectID()
	createdBy := primitive.NewObjectID()

	return &models.Event{
		// ID will be auto-generated by repository
		Title:         "Test Event",
		BrandID:       brandID,
		Summary:       "Test event summary",
		Status:        "draft",
		Visibility:    "public",
		CoverImageURL: "https://example.com/cover.jpg",
		Location: models.Location{
			Name:    "Test Venue",
			Address: "123 Test Street, Test City",
			PlaceID: "test-place-id",
			Coordinates: models.GeoJSONPoint{
				Type:        "Point",
				Coordinates: [2]float64{121.5654, 25.0330},
			},
		},
		Detail: models.Detail{
			Content:     "Test event detail content",
			ContentType: "html",
		},
		FAQ:       []models.FAQ{},
		CreatedBy: createdBy,
		UpdatedBy: createdBy,
	}
}

func (suite *EventRepositoryIntegrationTestSuite) TestCreate() {
	// Test creating a new event
	event := testEvent()
	// Don't set ID, let the repository generate it

	result, err := suite.repository.Create(suite.ctx, event)

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), result)
	assert.False(suite.T(), result.ID.IsZero())
	assert.Equal(suite.T(), event.BrandID, result.BrandID)
	assert.Equal(suite.T(), event.Title, result.Title)
	assert.Equal(suite.T(), event.Summary, result.Summary)
	assert.NotZero(suite.T(), result.CreatedAt)
	assert.NotZero(suite.T(), result.UpdatedAt)
}

func (suite *EventRepositoryIntegrationTestSuite) TestFindByID() {
	// Create an event first
	event := testEvent()
	created, err := suite.repository.Create(suite.ctx, event)
	suite.Require().NoError(err)

	// Test finding by ID
	found, err := suite.repository.FindByID(suite.ctx, created.ID.Hex())

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), found)
	assert.Equal(suite.T(), created.ID, found.ID)
	assert.Equal(suite.T(), created.Title, found.Title)
	assert.Equal(suite.T(), created.BrandID, found.BrandID)
}

func (suite *EventRepositoryIntegrationTestSuite) TestFindByIDNotFound() {
	// Test finding non-existent event
	objectID := primitive.NewObjectID()
	found, err := suite.repository.FindByID(suite.ctx, objectID.Hex())

	assert.Error(suite.T(), err)
	assert.Nil(suite.T(), found)
}

func (suite *EventRepositoryIntegrationTestSuite) TestUpdate() {
	// Create an event first
	event := testEvent()
	created, err := suite.repository.Create(suite.ctx, event)
	suite.Require().NoError(err)

	// Update the event
	created.Title = "Updated Event Title"
	created.Summary = "Updated summary"
	created.Status = "published"

	updated, err := suite.repository.Update(suite.ctx, created.ID.Hex(), created)

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), updated)
	assert.Equal(suite.T(), "Updated Event Title", updated.Title)
	assert.Equal(suite.T(), "Updated summary", updated.Summary)
	assert.Equal(suite.T(), "published", updated.Status)
	assert.True(suite.T(), updated.UpdatedAt.After(updated.CreatedAt))
}

func (suite *EventRepositoryIntegrationTestSuite) TestDelete() {
	// Create an event first
	event := testEvent()
	created, err := suite.repository.Create(suite.ctx, event)
	suite.Require().NoError(err)

	// Delete the event
	err = suite.repository.Delete(suite.ctx, created.ID.Hex())
	assert.NoError(suite.T(), err)

	// Verify it's deleted
	found, err := suite.repository.FindByID(suite.ctx, created.ID.Hex())
	assert.Error(suite.T(), err)
	assert.Nil(suite.T(), found)
}

func (suite *EventRepositoryIntegrationTestSuite) TestFindByBrandID() {
	brandID := primitive.NewObjectID()
	brandIDStr := brandID.Hex()

	// Create multiple events for the brand
	event1 := testEvent()
	event1.BrandID = brandID
	event1.Title = "Event 1"
	event1.Status = "draft"

	event2 := testEvent()
	event2.BrandID = brandID
	event2.Title = "Event 2"
	event2.Status = "published"

	// Create event for different brand
	event3 := testEvent()
	event3.BrandID = primitive.NewObjectID()
	event3.Title = "Other Event"

	_, err := suite.repository.Create(suite.ctx, event1)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, event2)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, event3)
	suite.Require().NoError(err)

	// Test finding by brand ID
	filter := &EventFilter{
		BrandID: &brandIDStr,
		Limit:   10,
		Offset:  0,
	}

	result, err := suite.repository.FindByBrandID(suite.ctx, brandIDStr, filter)

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), result)
	assert.Len(suite.T(), result.Events, 2)

	// Verify all events belong to the correct brand
	for _, event := range result.Events {
		assert.Equal(suite.T(), brandID, event.BrandID)
	}
}

func (suite *EventRepositoryIntegrationTestSuite) TestFindByBrandIDWithStatusFilter() {
	brandID := primitive.NewObjectID()
	brandIDStr := brandID.Hex()
	status := "published"

	// Create events with different statuses
	event1 := testEvent()
	event1.BrandID = brandID
	event1.Status = "draft"

	event2 := testEvent()
	event2.BrandID = brandID
	event2.Status = "published"

	_, err := suite.repository.Create(suite.ctx, event1)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, event2)
	suite.Require().NoError(err)

	// Test filtering by status
	filter := &EventFilter{
		BrandID: &brandIDStr,
		Status:  &status,
		Limit:   10,
		Offset:  0,
	}

	result, err := suite.repository.FindByBrandID(suite.ctx, brandIDStr, filter)

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), result)
	assert.Len(suite.T(), result.Events, 1)
	assert.Equal(suite.T(), "published", result.Events[0].Status)
}

func (suite *EventRepositoryIntegrationTestSuite) TestFindPublic() {
	// Create public and private events
	publicEvent1 := testEvent()
	publicEvent1.Status = "published"
	publicEvent1.Visibility = "public"
	publicEvent1.Title = "Public Event 1"

	publicEvent2 := testEvent()
	publicEvent2.Status = "published"
	publicEvent2.Visibility = "public"
	publicEvent2.Title = "Public Event 2"

	privateEvent := testEvent()
	privateEvent.Status = "published"
	privateEvent.Visibility = "private"
	privateEvent.Title = "Private Event"

	draftEvent := testEvent()
	draftEvent.Status = "draft"
	draftEvent.Visibility = "public"
	draftEvent.Title = "Draft Event"

	_, err := suite.repository.Create(suite.ctx, publicEvent1)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, publicEvent2)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, privateEvent)
	suite.Require().NoError(err)
	_, err = suite.repository.Create(suite.ctx, draftEvent)
	suite.Require().NoError(err)

	// Test finding public events
	filter := &PublicEventFilter{
		Limit:  10,
		Offset: 0,
	}

	result, err := suite.repository.FindPublic(suite.ctx, filter)

	assert.NoError(suite.T(), err)
	assert.NotNil(suite.T(), result)
	assert.Len(suite.T(), result.Events, 2)

	// Verify all events are public and published
	for _, event := range result.Events {
		assert.Equal(suite.T(), "published", event.Status)
		assert.Equal(suite.T(), "public", event.Visibility)
	}
}

func (suite *EventRepositoryIntegrationTestSuite) TestExistsByID() {
	// Create an event
	event := testEvent()
	created, err := suite.repository.Create(suite.ctx, event)
	suite.Require().NoError(err)

	// Test existence check for existing event
	exists, err := suite.repository.ExistsByID(suite.ctx, created.ID.Hex())
	assert.NoError(suite.T(), err)
	assert.True(suite.T(), exists)

	// Test existence check for non-existent event
	objectID := primitive.NewObjectID()
	exists, err = suite.repository.ExistsByID(suite.ctx, objectID.Hex())
	assert.NoError(suite.T(), err)
	assert.False(suite.T(), exists)
}

func (suite *EventRepositoryIntegrationTestSuite) TestExistsByBrandAndID() {
	brandID := primitive.NewObjectID()
	brandIDStr := brandID.Hex()

	// Create an event
	event := testEvent()
	event.BrandID = brandID
	created, err := suite.repository.Create(suite.ctx, event)
	suite.Require().NoError(err)

	// Test existence check for correct brand and ID
	exists, err := suite.repository.ExistsByBrandAndID(suite.ctx, brandIDStr, created.ID.Hex())
	assert.NoError(suite.T(), err)
	assert.True(suite.T(), exists)

	// Test existence check for wrong brand
	exists, err = suite.repository.ExistsByBrandAndID(suite.ctx, "wrong-brand", created.ID.Hex())
	assert.NoError(suite.T(), err)
	assert.False(suite.T(), exists)

	// Test existence check for non-existent event
	objectID := primitive.NewObjectID()
	exists, err = suite.repository.ExistsByBrandAndID(suite.ctx, brandIDStr, objectID.Hex())
	assert.NoError(suite.T(), err)
	assert.False(suite.T(), exists)
}

func TestEventRepositoryIntegrationTestSuite(t *testing.T) {
	suite.Run(t, new(EventRepositoryIntegrationTestSuite))
}
