// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/event/event.proto

package event

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Event) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EventMultiError, or nil if none found.
func (m *Event) ValidateAll() error {
	return m.validate(true)
}

func (m *Event) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for BrandId

	// no validation rules for Summary

	// no validation rules for Status

	// no validation rules for Visibility

	// no validation rules for CoverImageUrl

	if all {
		switch v := interface{}(m.GetLocation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventValidationError{
				field:  "Location",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetSessions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventValidationError{
					field:  fmt.Sprintf("Sessions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetDetail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventValidationError{
				field:  "Detail",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetFaq() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventValidationError{
					field:  fmt.Sprintf("Faq[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CreatedAt

	// no validation rules for CreatedBy

	// no validation rules for UpdatedAt

	// no validation rules for UpdatedBy

	if len(errors) > 0 {
		return EventMultiError(errors)
	}

	return nil
}

// EventMultiError is an error wrapping multiple validation errors returned by
// Event.ValidateAll() if the designated constraints aren't met.
type EventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventMultiError) AllErrors() []error { return m }

// EventValidationError is the validation error returned by Event.Validate if
// the designated constraints aren't met.
type EventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventValidationError) ErrorName() string { return "EventValidationError" }

// Error satisfies the builtin error interface
func (e EventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventValidationError{}

// Validate checks the field values on Location with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Location) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Location with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LocationMultiError, or nil
// if none found.
func (m *Location) ValidateAll() error {
	return m.validate(true)
}

func (m *Location) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := LocationValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAddress()) < 1 {
		err := LocationValidationError{
			field:  "Address",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPlaceId()) < 1 {
		err := LocationValidationError{
			field:  "PlaceId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCoordinates() == nil {
		err := LocationValidationError{
			field:  "Coordinates",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCoordinates()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LocationValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LocationValidationError{
					field:  "Coordinates",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LocationValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LocationMultiError(errors)
	}

	return nil
}

// LocationMultiError is an error wrapping multiple validation errors returned
// by Location.ValidateAll() if the designated constraints aren't met.
type LocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocationMultiError) AllErrors() []error { return m }

// LocationValidationError is the validation error returned by
// Location.Validate if the designated constraints aren't met.
type LocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocationValidationError) ErrorName() string { return "LocationValidationError" }

// Error satisfies the builtin error interface
func (e LocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocationValidationError{}

// Validate checks the field values on GeoJSONPoint with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GeoJSONPoint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GeoJSONPoint with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GeoJSONPointMultiError, or
// nil if none found.
func (m *GeoJSONPoint) ValidateAll() error {
	return m.validate(true)
}

func (m *GeoJSONPoint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetType() != "Point" {
		err := GeoJSONPointValidationError{
			field:  "Type",
			reason: "value must equal Point",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetCoordinates()) != 2 {
		err := GeoJSONPointValidationError{
			field:  "Coordinates",
			reason: "value must contain exactly 2 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GeoJSONPointMultiError(errors)
	}

	return nil
}

// GeoJSONPointMultiError is an error wrapping multiple validation errors
// returned by GeoJSONPoint.ValidateAll() if the designated constraints aren't met.
type GeoJSONPointMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GeoJSONPointMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GeoJSONPointMultiError) AllErrors() []error { return m }

// GeoJSONPointValidationError is the validation error returned by
// GeoJSONPoint.Validate if the designated constraints aren't met.
type GeoJSONPointValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GeoJSONPointValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GeoJSONPointValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GeoJSONPointValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GeoJSONPointValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GeoJSONPointValidationError) ErrorName() string { return "GeoJSONPointValidationError" }

// Error satisfies the builtin error interface
func (e GeoJSONPointValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGeoJSONPoint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GeoJSONPointValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GeoJSONPointValidationError{}

// Validate checks the field values on Session with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Session) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Session with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SessionMultiError, or nil if none found.
func (m *Session) ValidateAll() error {
	return m.validate(true)
}

func (m *Session) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return SessionMultiError(errors)
	}

	return nil
}

// SessionMultiError is an error wrapping multiple validation errors returned
// by Session.ValidateAll() if the designated constraints aren't met.
type SessionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SessionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SessionMultiError) AllErrors() []error { return m }

// SessionValidationError is the validation error returned by Session.Validate
// if the designated constraints aren't met.
type SessionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SessionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SessionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SessionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SessionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SessionValidationError) ErrorName() string { return "SessionValidationError" }

// Error satisfies the builtin error interface
func (e SessionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSession.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SessionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SessionValidationError{}

// Validate checks the field values on Detail with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Detail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Detail with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DetailMultiError, or nil if none found.
func (m *Detail) ValidateAll() error {
	return m.validate(true)
}

func (m *Detail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetContent()) > 65536 {
		err := DetailValidationError{
			field:  "Content",
			reason: "value length must be at most 65536 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetContentType() != "" {

		if _, ok := _Detail_ContentType_InLookup[m.GetContentType()]; !ok {
			err := DetailValidationError{
				field:  "ContentType",
				reason: "value must be in list [html markdown plain]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return DetailMultiError(errors)
	}

	return nil
}

// DetailMultiError is an error wrapping multiple validation errors returned by
// Detail.ValidateAll() if the designated constraints aren't met.
type DetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailMultiError) AllErrors() []error { return m }

// DetailValidationError is the validation error returned by Detail.Validate if
// the designated constraints aren't met.
type DetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailValidationError) ErrorName() string { return "DetailValidationError" }

// Error satisfies the builtin error interface
func (e DetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailValidationError{}

var _Detail_ContentType_InLookup = map[string]struct{}{
	"html":     {},
	"markdown": {},
	"plain":    {},
}

// Validate checks the field values on FAQ with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *FAQ) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FAQ with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FAQMultiError, or nil if none found.
func (m *FAQ) ValidateAll() error {
	return m.validate(true)
}

func (m *FAQ) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetQuestion()); l < 1 || l > 100 {
		err := FAQValidationError{
			field:  "Question",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetAnswer()); l < 1 || l > 300 {
		err := FAQValidationError{
			field:  "Answer",
			reason: "value length must be between 1 and 300 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return FAQMultiError(errors)
	}

	return nil
}

// FAQMultiError is an error wrapping multiple validation errors returned by
// FAQ.ValidateAll() if the designated constraints aren't met.
type FAQMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FAQMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FAQMultiError) AllErrors() []error { return m }

// FAQValidationError is the validation error returned by FAQ.Validate if the
// designated constraints aren't met.
type FAQValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FAQValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FAQValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FAQValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FAQValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FAQValidationError) ErrorName() string { return "FAQValidationError" }

// Error satisfies the builtin error interface
func (e FAQValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFAQ.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FAQValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FAQValidationError{}

// Validate checks the field values on CreateEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateEventRequestMultiError, or nil if none found.
func (m *CreateEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 60 {
		err := CreateEventRequestValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 60 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSummary()) > 160 {
		err := CreateEventRequestValidationError{
			field:  "Summary",
			reason: "value length must be at most 160 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetVisibility() != "" {

		if _, ok := _CreateEventRequest_Visibility_InLookup[m.GetVisibility()]; !ok {
			err := CreateEventRequestValidationError{
				field:  "Visibility",
				reason: "value must be in list [public private]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetCoverImageUrl() != "" {

		if uri, err := url.Parse(m.GetCoverImageUrl()); err != nil {
			err = CreateEventRequestValidationError{
				field:  "CoverImageUrl",
				reason: "value must be a valid URI",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else if !uri.IsAbs() {
			err := CreateEventRequestValidationError{
				field:  "CoverImageUrl",
				reason: "value must be absolute",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	for idx, item := range m.GetSessions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateEventRequestValidationError{
					field:  fmt.Sprintf("Sessions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(m.GetFaq()) > 20 {
		err := CreateEventRequestValidationError{
			field:  "Faq",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetFaq() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateEventRequestValidationError{
					field:  fmt.Sprintf("Faq[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Location != nil {

		if all {
			switch v := interface{}(m.GetLocation()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  "Location",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  "Location",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateEventRequestValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Detail != nil {

		if all {
			switch v := interface{}(m.GetDetail()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  "Detail",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateEventRequestValidationError{
						field:  "Detail",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDetail()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateEventRequestValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateEventRequestMultiError(errors)
	}

	return nil
}

// CreateEventRequestMultiError is an error wrapping multiple validation errors
// returned by CreateEventRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateEventRequestMultiError) AllErrors() []error { return m }

// CreateEventRequestValidationError is the validation error returned by
// CreateEventRequest.Validate if the designated constraints aren't met.
type CreateEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateEventRequestValidationError) ErrorName() string {
	return "CreateEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateEventRequestValidationError{}

var _CreateEventRequest_Visibility_InLookup = map[string]struct{}{
	"public":  {},
	"private": {},
}

// Validate checks the field values on GetEventListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEventListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventListRequestMultiError, or nil if none found.
func (m *GetEventListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if m.Page != nil {

		if m.GetPage() < 1 {
			err := GetEventListRequestValidationError{
				field:  "Page",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.PageSize != nil {

		if val := m.GetPageSize(); val < 1 || val > 100 {
			err := GetEventListRequestValidationError{
				field:  "PageSize",
				reason: "value must be inside range [1, 100]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Status != nil {

		if m.GetStatus() != "" {

			if _, ok := _GetEventListRequest_Status_InLookup[m.GetStatus()]; !ok {
				err := GetEventListRequestValidationError{
					field:  "Status",
					reason: "value must be in list [draft published archived]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Visibility != nil {

		if m.GetVisibility() != "" {

			if _, ok := _GetEventListRequest_Visibility_InLookup[m.GetVisibility()]; !ok {
				err := GetEventListRequestValidationError{
					field:  "Visibility",
					reason: "value must be in list [public private]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.SessionStartTimeFrom != nil {
		// no validation rules for SessionStartTimeFrom
	}

	if m.SessionStartTimeTo != nil {
		// no validation rules for SessionStartTimeTo
	}

	if m.TitleSearch != nil {
		// no validation rules for TitleSearch
	}

	if m.SortBy != nil {

		if m.GetSortBy() != "" {

			if _, ok := _GetEventListRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
				err := GetEventListRequestValidationError{
					field:  "SortBy",
					reason: "value must be in list [created_at updated_at session_start_time]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.SortOrder != nil {

		if m.GetSortOrder() != "" {

			if _, ok := _GetEventListRequest_SortOrder_InLookup[m.GetSortOrder()]; !ok {
				err := GetEventListRequestValidationError{
					field:  "SortOrder",
					reason: "value must be in list [asc desc]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return GetEventListRequestMultiError(errors)
	}

	return nil
}

// GetEventListRequestMultiError is an error wrapping multiple validation
// errors returned by GetEventListRequest.ValidateAll() if the designated
// constraints aren't met.
type GetEventListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventListRequestMultiError) AllErrors() []error { return m }

// GetEventListRequestValidationError is the validation error returned by
// GetEventListRequest.Validate if the designated constraints aren't met.
type GetEventListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventListRequestValidationError) ErrorName() string {
	return "GetEventListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEventListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventListRequestValidationError{}

var _GetEventListRequest_Status_InLookup = map[string]struct{}{
	"draft":     {},
	"published": {},
	"archived":  {},
}

var _GetEventListRequest_Visibility_InLookup = map[string]struct{}{
	"public":  {},
	"private": {},
}

var _GetEventListRequest_SortBy_InLookup = map[string]struct{}{
	"created_at":         {},
	"updated_at":         {},
	"session_start_time": {},
}

var _GetEventListRequest_SortOrder_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

// Validate checks the field values on PatchEventRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PatchEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PatchEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PatchEventRequestMultiError, or nil if none found.
func (m *PatchEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PatchEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := PatchEventRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetSessions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchEventRequestValidationError{
					field:  fmt.Sprintf("Sessions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(m.GetFaq()) > 20 {
		err := PatchEventRequestValidationError{
			field:  "Faq",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetFaq() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  fmt.Sprintf("Faq[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchEventRequestValidationError{
					field:  fmt.Sprintf("Faq[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Title != nil {

		if m.GetTitle() != "" {

			if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 60 {
				err := PatchEventRequestValidationError{
					field:  "Title",
					reason: "value length must be between 1 and 60 runes, inclusive",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Summary != nil {

		if m.GetSummary() != "" {

			if utf8.RuneCountInString(m.GetSummary()) > 160 {
				err := PatchEventRequestValidationError{
					field:  "Summary",
					reason: "value length must be at most 160 runes",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Status != nil {

		if m.GetStatus() != "" {

			if _, ok := _PatchEventRequest_Status_InLookup[m.GetStatus()]; !ok {
				err := PatchEventRequestValidationError{
					field:  "Status",
					reason: "value must be in list [draft published archived]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Visibility != nil {

		if m.GetVisibility() != "" {

			if _, ok := _PatchEventRequest_Visibility_InLookup[m.GetVisibility()]; !ok {
				err := PatchEventRequestValidationError{
					field:  "Visibility",
					reason: "value must be in list [public private]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.CoverImageUrl != nil {

		if m.GetCoverImageUrl() != "" {

			if uri, err := url.Parse(m.GetCoverImageUrl()); err != nil {
				err = PatchEventRequestValidationError{
					field:  "CoverImageUrl",
					reason: "value must be a valid URI",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			} else if !uri.IsAbs() {
				err := PatchEventRequestValidationError{
					field:  "CoverImageUrl",
					reason: "value must be absolute",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.Location != nil {

		if all {
			switch v := interface{}(m.GetLocation()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  "Location",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  "Location",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchEventRequestValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Detail != nil {

		if all {
			switch v := interface{}(m.GetDetail()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  "Detail",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PatchEventRequestValidationError{
						field:  "Detail",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDetail()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PatchEventRequestValidationError{
					field:  "Detail",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PatchEventRequestMultiError(errors)
	}

	return nil
}

// PatchEventRequestMultiError is an error wrapping multiple validation errors
// returned by PatchEventRequest.ValidateAll() if the designated constraints
// aren't met.
type PatchEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PatchEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PatchEventRequestMultiError) AllErrors() []error { return m }

// PatchEventRequestValidationError is the validation error returned by
// PatchEventRequest.Validate if the designated constraints aren't met.
type PatchEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PatchEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PatchEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PatchEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PatchEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PatchEventRequestValidationError) ErrorName() string {
	return "PatchEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PatchEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPatchEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PatchEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PatchEventRequestValidationError{}

var _PatchEventRequest_Status_InLookup = map[string]struct{}{
	"draft":     {},
	"published": {},
	"archived":  {},
}

var _PatchEventRequest_Visibility_InLookup = map[string]struct{}{
	"public":  {},
	"private": {},
}

// Validate checks the field values on UpdateEventStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateEventStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEventStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateEventStatusRequestMultiError, or nil if none found.
func (m *UpdateEventStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEventStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateEventStatusRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _UpdateEventStatusRequest_Status_InLookup[m.GetStatus()]; !ok {
		err := UpdateEventStatusRequestValidationError{
			field:  "Status",
			reason: "value must be in list [draft published archived]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateEventStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateEventStatusRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateEventStatusRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateEventStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEventStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEventStatusRequestMultiError) AllErrors() []error { return m }

// UpdateEventStatusRequestValidationError is the validation error returned by
// UpdateEventStatusRequest.Validate if the designated constraints aren't met.
type UpdateEventStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEventStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEventStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEventStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEventStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEventStatusRequestValidationError) ErrorName() string {
	return "UpdateEventStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEventStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEventStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEventStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEventStatusRequestValidationError{}

var _UpdateEventStatusRequest_Status_InLookup = map[string]struct{}{
	"draft":     {},
	"published": {},
	"archived":  {},
}

// Validate checks the field values on DeleteSessionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteSessionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteSessionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteSessionRequestMultiError, or nil if none found.
func (m *DeleteSessionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteSessionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetEventId()) < 1 {
		err := DeleteSessionRequestValidationError{
			field:  "EventId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSessionId()) < 1 {
		err := DeleteSessionRequestValidationError{
			field:  "SessionId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteSessionRequestMultiError(errors)
	}

	return nil
}

// DeleteSessionRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteSessionRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteSessionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteSessionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteSessionRequestMultiError) AllErrors() []error { return m }

// DeleteSessionRequestValidationError is the validation error returned by
// DeleteSessionRequest.Validate if the designated constraints aren't met.
type DeleteSessionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteSessionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteSessionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteSessionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteSessionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteSessionRequestValidationError) ErrorName() string {
	return "DeleteSessionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteSessionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteSessionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteSessionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteSessionRequestValidationError{}

// Validate checks the field values on SearchEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchEventsRequestMultiError, or nil if none found.
func (m *SearchEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if m.Page != nil {

		if m.GetPage() < 1 {
			err := SearchEventsRequestValidationError{
				field:  "Page",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.PageSize != nil {

		if val := m.GetPageSize(); val < 1 || val > 100 {
			err := SearchEventsRequestValidationError{
				field:  "PageSize",
				reason: "value must be inside range [1, 100]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.BrandId != nil {
		// no validation rules for BrandId
	}

	if m.TitleSearch != nil {
		// no validation rules for TitleSearch
	}

	if m.SessionStartTimeFrom != nil {
		// no validation rules for SessionStartTimeFrom
	}

	if m.SessionStartTimeTo != nil {
		// no validation rules for SessionStartTimeTo
	}

	if m.LocationLat != nil {

		if val := m.GetLocationLat(); val < -90 || val > 90 {
			err := SearchEventsRequestValidationError{
				field:  "LocationLat",
				reason: "value must be inside range [-90, 90]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.LocationLng != nil {

		if val := m.GetLocationLng(); val < -180 || val > 180 {
			err := SearchEventsRequestValidationError{
				field:  "LocationLng",
				reason: "value must be inside range [-180, 180]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.LocationRadius != nil {

		if m.GetLocationRadius() < 1 {
			err := SearchEventsRequestValidationError{
				field:  "LocationRadius",
				reason: "value must be greater than or equal to 1",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.SortBy != nil {

		if m.GetSortBy() != "" {

			if _, ok := _SearchEventsRequest_SortBy_InLookup[m.GetSortBy()]; !ok {
				err := SearchEventsRequestValidationError{
					field:  "SortBy",
					reason: "value must be in list [session_start_time created_at]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.SortOrder != nil {

		if m.GetSortOrder() != "" {

			if _, ok := _SearchEventsRequest_SortOrder_InLookup[m.GetSortOrder()]; !ok {
				err := SearchEventsRequestValidationError{
					field:  "SortOrder",
					reason: "value must be in list [asc desc]",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return SearchEventsRequestMultiError(errors)
	}

	return nil
}

// SearchEventsRequestMultiError is an error wrapping multiple validation
// errors returned by SearchEventsRequest.ValidateAll() if the designated
// constraints aren't met.
type SearchEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchEventsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchEventsRequestMultiError) AllErrors() []error { return m }

// SearchEventsRequestValidationError is the validation error returned by
// SearchEventsRequest.Validate if the designated constraints aren't met.
type SearchEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchEventsRequestValidationError) ErrorName() string {
	return "SearchEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchEventsRequestValidationError{}

var _SearchEventsRequest_SortBy_InLookup = map[string]struct{}{
	"session_start_time": {},
	"created_at":         {},
}

var _SearchEventsRequest_SortOrder_InLookup = map[string]struct{}{
	"asc":  {},
	"desc": {},
}

// Validate checks the field values on EventResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventResponseMultiError, or
// nil if none found.
func (m *EventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *EventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventResponseValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EventResponseMultiError(errors)
	}

	return nil
}

// EventResponseMultiError is an error wrapping multiple validation errors
// returned by EventResponse.ValidateAll() if the designated constraints
// aren't met.
type EventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventResponseMultiError) AllErrors() []error { return m }

// EventResponseValidationError is the validation error returned by
// EventResponse.Validate if the designated constraints aren't met.
type EventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventResponseValidationError) ErrorName() string { return "EventResponseValidationError" }

// Error satisfies the builtin error interface
func (e EventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventResponseValidationError{}

// Validate checks the field values on EventListResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EventListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EventListResponseMultiError, or nil if none found.
func (m *EventListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *EventListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventListResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventListResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventListResponseValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventListResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventListResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventListResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return EventListResponseMultiError(errors)
	}

	return nil
}

// EventListResponseMultiError is an error wrapping multiple validation errors
// returned by EventListResponse.ValidateAll() if the designated constraints
// aren't met.
type EventListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventListResponseMultiError) AllErrors() []error { return m }

// EventListResponseValidationError is the validation error returned by
// EventListResponse.Validate if the designated constraints aren't met.
type EventListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventListResponseValidationError) ErrorName() string {
	return "EventListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e EventListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventListResponseValidationError{}

// Validate checks the field values on Pagination with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Pagination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Pagination with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationMultiError, or
// nil if none found.
func (m *Pagination) ValidateAll() error {
	return m.validate(true)
}

func (m *Pagination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.NextPageToken != nil {
		// no validation rules for NextPageToken
	}

	if m.PrevPageToken != nil {
		// no validation rules for PrevPageToken
	}

	if m.HasNext != nil {
		// no validation rules for HasNext
	}

	if m.HasPrev != nil {
		// no validation rules for HasPrev
	}

	if m.TotalCount != nil {
		// no validation rules for TotalCount
	}

	if m.CurrentPage != nil {
		// no validation rules for CurrentPage
	}

	if m.TotalPages != nil {
		// no validation rules for TotalPages
	}

	if len(errors) > 0 {
		return PaginationMultiError(errors)
	}

	return nil
}

// PaginationMultiError is an error wrapping multiple validation errors
// returned by Pagination.ValidateAll() if the designated constraints aren't met.
type PaginationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationMultiError) AllErrors() []error { return m }

// PaginationValidationError is the validation error returned by
// Pagination.Validate if the designated constraints aren't met.
type PaginationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationValidationError) ErrorName() string { return "PaginationValidationError" }

// Error satisfies the builtin error interface
func (e PaginationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPagination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationValidationError{}
