// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/event/event.proto

package event

import (
	api "event/api"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core Event message
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	BrandId       string                 `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`         // draft, published, archived
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"` // public, private
	CoverImageUrl string                 `protobuf:"bytes,7,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Location      *Location              `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Sessions      []*Session             `protobuf:"bytes,9,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Detail        *Detail                `protobuf:"bytes,10,opt,name=detail,proto3" json:"detail,omitempty"`
	Faq           []*FAQ                 `protobuf:"bytes,11,rep,name=faq,proto3" json:"faq,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,15,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Event) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Event) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Event) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Event) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *Event) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Event) GetFaq() []*FAQ {
	if x != nil {
		return x.Faq
	}
	return nil
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Event) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Event) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// Location with GeoJSON Point structure
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PlaceId       string                 `protobuf:"bytes,3,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Coordinates   *GeoJSONPoint          `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_event_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Location) GetCoordinates() *GeoJSONPoint {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type GeoJSONPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                        // Always "Point"
	Coordinates   []float64              `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"` // [longitude, latitude]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoJSONPoint) Reset() {
	*x = GeoJSONPoint{}
	mi := &file_api_event_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoJSONPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoJSONPoint) ProtoMessage() {}

func (x *GeoJSONPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoJSONPoint.ProtoReflect.Descriptor instead.
func (*GeoJSONPoint) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *GeoJSONPoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeoJSONPoint) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// Session for time-based event scheduling
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // Session name (optional)
	Capacity      *int32                 `protobuf:"varint,3,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`             // Capacity limit (optional, null means unlimited)
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // RFC3339 format
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_event_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetCapacity() int32 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

func (x *Session) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Session) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// Event detail content
type Detail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // html, json, markdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_api_event_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *Detail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Detail) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// FAQ entry
type FAQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FAQ) Reset() {
	*x = FAQ{}
	mi := &file_api_event_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FAQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FAQ) ProtoMessage() {}

func (x *FAQ) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FAQ.ProtoReflect.Descriptor instead.
func (*FAQ) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{5}
}

func (x *FAQ) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *FAQ) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// Request messages
type CreateEventRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Title   string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// status field removed - events are always created as draft
	Visibility    string     `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CoverImageUrl string     `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Location      *Location  `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Sessions      []*Session `protobuf:"bytes,6,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Detail        *Detail    `protobuf:"bytes,7,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Faq           []*FAQ     `protobuf:"bytes,8,rep,name=faq,proto3" json:"faq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_event_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateEventRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateEventRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateEventRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CreateEventRequest) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *CreateEventRequest) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *CreateEventRequest) GetFaq() []*FAQ {
	if x != nil {
		return x.Faq
	}
	return nil
}

type GetEventListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination
	PageToken *string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"` // for cursor-based pagination
	Page      *int32  `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`                           // for page-based pagination
	PageSize  *int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`   // default 20, max 100
	// Filters
	Status               *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`                                                             // draft|published|archived
	Visibility           *string `protobuf:"bytes,5,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`                                                     // public|private
	SessionStartTimeFrom *string `protobuf:"bytes,6,opt,name=session_start_time_from,json=sessionStartTimeFrom,proto3,oneof" json:"session_start_time_from,omitempty"` // RFC3339
	SessionStartTimeTo   *string `protobuf:"bytes,7,opt,name=session_start_time_to,json=sessionStartTimeTo,proto3,oneof" json:"session_start_time_to,omitempty"`       // RFC3339
	TitleSearch          *string `protobuf:"bytes,8,opt,name=title_search,json=titleSearch,proto3,oneof" json:"title_search,omitempty"`                                // full-text search
	// Sorting
	SortBy        *string `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`           // created_at|updated_at|session_start_time
	SortOrder     *string `protobuf:"bytes,10,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"` // asc|desc, default desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListRequest) Reset() {
	*x = GetEventListRequest{}
	mi := &file_api_event_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListRequest) ProtoMessage() {}

func (x *GetEventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListRequest.ProtoReflect.Descriptor instead.
func (*GetEventListRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventListRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *GetEventListRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetEventListRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *GetEventListRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetEventListRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *GetEventListRequest) GetSessionStartTimeFrom() string {
	if x != nil && x.SessionStartTimeFrom != nil {
		return *x.SessionStartTimeFrom
	}
	return ""
}

func (x *GetEventListRequest) GetSessionStartTimeTo() string {
	if x != nil && x.SessionStartTimeTo != nil {
		return *x.SessionStartTimeTo
	}
	return ""
}

func (x *GetEventListRequest) GetTitleSearch() string {
	if x != nil && x.TitleSearch != nil {
		return *x.TitleSearch
	}
	return ""
}

func (x *GetEventListRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *GetEventListRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

type PatchEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Summary       *string                `protobuf:"bytes,3,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Visibility    *string                `protobuf:"bytes,5,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	CoverImageUrl *string                `protobuf:"bytes,6,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Location      *Location              `protobuf:"bytes,7,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Sessions      []*Session             `protobuf:"bytes,8,rep,name=sessions,proto3" json:"sessions,omitempty"` // Replace all sessions if provided
	Detail        *Detail                `protobuf:"bytes,9,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Faq           []*FAQ                 `protobuf:"bytes,10,rep,name=faq,proto3" json:"faq,omitempty"` // Replace all FAQ if provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchEventRequest) Reset() {
	*x = PatchEventRequest{}
	mi := &file_api_event_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchEventRequest) ProtoMessage() {}

func (x *PatchEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchEventRequest.ProtoReflect.Descriptor instead.
func (*PatchEventRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *PatchEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchEventRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PatchEventRequest) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *PatchEventRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *PatchEventRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *PatchEventRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *PatchEventRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *PatchEventRequest) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *PatchEventRequest) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *PatchEventRequest) GetFaq() []*FAQ {
	if x != nil {
		return x.Faq
	}
	return nil
}

type UpdateEventStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // draft|published|archived
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventStatusRequest) Reset() {
	*x = UpdateEventStatusRequest{}
	mi := &file_api_event_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventStatusRequest) ProtoMessage() {}

func (x *UpdateEventStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEventStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_api_event_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSessionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SearchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination
	PageToken *string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	Page      *int32  `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize  *int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Filters
	BrandId              *string `protobuf:"bytes,4,opt,name=brand_id,json=brandId,proto3,oneof" json:"brand_id,omitempty"`             // filter by specific brand
	TitleSearch          *string `protobuf:"bytes,5,opt,name=title_search,json=titleSearch,proto3,oneof" json:"title_search,omitempty"` // full-text search
	SessionStartTimeFrom *string `protobuf:"bytes,6,opt,name=session_start_time_from,json=sessionStartTimeFrom,proto3,oneof" json:"session_start_time_from,omitempty"`
	SessionStartTimeTo   *string `protobuf:"bytes,7,opt,name=session_start_time_to,json=sessionStartTimeTo,proto3,oneof" json:"session_start_time_to,omitempty"`
	// Location-based search
	LocationLat    *float64 `protobuf:"fixed64,8,opt,name=location_lat,json=locationLat,proto3,oneof" json:"location_lat,omitempty"`
	LocationLng    *float64 `protobuf:"fixed64,9,opt,name=location_lng,json=locationLng,proto3,oneof" json:"location_lng,omitempty"`
	LocationRadius *int32   `protobuf:"varint,10,opt,name=location_radius,json=locationRadius,proto3,oneof" json:"location_radius,omitempty"` // in meters, default 1000
	// Sorting
	SortBy        *string `protobuf:"bytes,11,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`          // session_start_time|created_at
	SortOrder     *string `protobuf:"bytes,12,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"` // asc|desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsRequest) Reset() {
	*x = SearchEventsRequest{}
	mi := &file_api_event_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsRequest) ProtoMessage() {}

func (x *SearchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsRequest.ProtoReflect.Descriptor instead.
func (*SearchEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{11}
}

func (x *SearchEventsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *SearchEventsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *SearchEventsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *SearchEventsRequest) GetBrandId() string {
	if x != nil && x.BrandId != nil {
		return *x.BrandId
	}
	return ""
}

func (x *SearchEventsRequest) GetTitleSearch() string {
	if x != nil && x.TitleSearch != nil {
		return *x.TitleSearch
	}
	return ""
}

func (x *SearchEventsRequest) GetSessionStartTimeFrom() string {
	if x != nil && x.SessionStartTimeFrom != nil {
		return *x.SessionStartTimeFrom
	}
	return ""
}

func (x *SearchEventsRequest) GetSessionStartTimeTo() string {
	if x != nil && x.SessionStartTimeTo != nil {
		return *x.SessionStartTimeTo
	}
	return ""
}

func (x *SearchEventsRequest) GetLocationLat() float64 {
	if x != nil && x.LocationLat != nil {
		return *x.LocationLat
	}
	return 0
}

func (x *SearchEventsRequest) GetLocationLng() float64 {
	if x != nil && x.LocationLng != nil {
		return *x.LocationLng
	}
	return 0
}

func (x *SearchEventsRequest) GetLocationRadius() int32 {
	if x != nil && x.LocationRadius != nil {
		return *x.LocationRadius
	}
	return 0
}

func (x *SearchEventsRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *SearchEventsRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

// Response messages
type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_event_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateEventResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type EventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_api_event_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResponse.ProtoReflect.Descriptor instead.
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{13}
}

func (x *EventListResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken *string                `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"` // for cursor-based
	PrevPageToken *string                `protobuf:"bytes,2,opt,name=prev_page_token,json=prevPageToken,proto3,oneof" json:"prev_page_token,omitempty"` // for cursor-based
	HasNext       *bool                  `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3,oneof" json:"has_next,omitempty"`
	HasPrev       *bool                  `protobuf:"varint,4,opt,name=has_prev,json=hasPrev,proto3,oneof" json:"has_prev,omitempty"`
	TotalCount    *int32                 `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	CurrentPage   *int32                 `protobuf:"varint,6,opt,name=current_page,json=currentPage,proto3,oneof" json:"current_page,omitempty"` // for page-based
	TotalPages    *int32                 `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3,oneof" json:"total_pages,omitempty"`    // for page-based
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_event_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{14}
}

func (x *Pagination) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

func (x *Pagination) GetPrevPageToken() string {
	if x != nil && x.PrevPageToken != nil {
		return *x.PrevPageToken
	}
	return ""
}

func (x *Pagination) GetHasNext() bool {
	if x != nil && x.HasNext != nil {
		return *x.HasNext
	}
	return false
}

func (x *Pagination) GetHasPrev() bool {
	if x != nil && x.HasPrev != nil {
		return *x.HasPrev
	}
	return false
}

func (x *Pagination) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil && x.CurrentPage != nil {
		return *x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil && x.TotalPages != nil {
		return *x.TotalPages
	}
	return 0
}

// Response for IsPublished API
type IsPublishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPublished   bool                   `protobuf:"varint,1,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Current status of the event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsPublishedResponse) Reset() {
	*x = IsPublishedResponse{}
	mi := &file_api_event_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPublishedResponse) ProtoMessage() {}

func (x *IsPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPublishedResponse.ProtoReflect.Descriptor instead.
func (*IsPublishedResponse) Descriptor() ([]byte, []int) {
	return file_api_event_event_proto_rawDescGZIP(), []int{15}
}

func (x *IsPublishedResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *IsPublishedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_event_event_proto protoreflect.FileDescriptor

const file_api_event_event_proto_rawDesc = "" +
	"\n" +
	"\x15api/event/event.proto\x12\x05event\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10api/common.proto\x1a#third_party/validate/validate.proto\"\xdc\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bbrand_id\x18\x03 \x01(\tR\abrandId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12&\n" +
	"\x0fcover_image_url\x18\a \x01(\tR\rcoverImageUrl\x12+\n" +
	"\blocation\x18\b \x01(\v2\x0f.event.LocationR\blocation\x12*\n" +
	"\bsessions\x18\t \x03(\v2\x0e.event.SessionR\bsessions\x12%\n" +
	"\x06detail\x18\n" +
	" \x01(\v2\r.event.DetailR\x06detail\x12\x1c\n" +
	"\x03faq\x18\v \x03(\v2\n" +
	".event.FAQR\x03faq\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\r \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x0f \x01(\tR\tupdatedBy\"\xaf\x01\n" +
	"\bLocation\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12!\n" +
	"\aaddress\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aaddress\x12\"\n" +
	"\bplace_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aplaceId\x12?\n" +
	"\vcoordinates\x18\x04 \x01(\v2\x13.event.GeoJSONPointB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vcoordinates\"^\n" +
	"\fGeoJSONPoint\x12 \n" +
	"\x04type\x18\x01 \x01(\tB\f\xfaB\tr\a\n" +
	"\x05PointR\x04type\x12,\n" +
	"\vcoordinates\x18\x02 \x03(\x01B\n" +
	"\xfaB\a\x92\x01\x04\b\x02\x10\x02R\vcoordinates\"\x95\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\bcapacity\x18\x03 \x01(\x05H\x00R\bcapacity\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTimeB\v\n" +
	"\t_capacity\"q\n" +
	"\x06Detail\x12#\n" +
	"\acontent\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x18\x80\x80\x04R\acontent\x12B\n" +
	"\fcontent_type\x18\x02 \x01(\tB\x1f\xfaB\x1cr\x1aR\x04htmlR\bmarkdownR\x05plain\xd0\x01\x01R\vcontentType\"P\n" +
	"\x03FAQ\x12%\n" +
	"\bquestion\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\bquestion\x12\"\n" +
	"\x06answer\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xac\x02R\x06answer\"\x95\x03\n" +
	"\x12CreateEventRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x05title\x12\"\n" +
	"\asummary\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xa0\x01R\asummary\x129\n" +
	"\n" +
	"visibility\x18\x03 \x01(\tB\x19\xfaB\x16r\x14R\x06publicR\aprivate\xd0\x01\x01R\n" +
	"visibility\x123\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tB\v\xfaB\br\x06\xd0\x01\x01\x88\x01\x01R\rcoverImageUrl\x120\n" +
	"\blocation\x18\x05 \x01(\v2\x0f.event.LocationH\x00R\blocation\x88\x01\x01\x12*\n" +
	"\bsessions\x18\x06 \x03(\v2\x0e.event.SessionR\bsessions\x12*\n" +
	"\x06detail\x18\a \x01(\v2\r.event.DetailH\x01R\x06detail\x88\x01\x01\x12(\n" +
	"\x03faq\x18\b \x03(\v2\n" +
	".event.FAQB\n" +
	"\xfaB\a\x92\x01\x04\b\x00\x10\x14R\x03faqB\v\n" +
	"\t_locationB\t\n" +
	"\a_detail\"\xd6\x05\n" +
	"\x13GetEventListRequest\x12\"\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tH\x00R\tpageToken\x88\x01\x01\x12 \n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01H\x01R\x04page\x88\x01\x01\x12+\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01H\x02R\bpageSize\x88\x01\x01\x12A\n" +
	"\x06status\x18\x04 \x01(\tB$\xfaB!r\x1fR\x05draftR\tpublishedR\barchived\xd0\x01\x01H\x03R\x06status\x88\x01\x01\x12>\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tB\x19\xfaB\x16r\x14R\x06publicR\aprivate\xd0\x01\x01H\x04R\n" +
	"visibility\x88\x01\x01\x12:\n" +
	"\x17session_start_time_from\x18\x06 \x01(\tH\x05R\x14sessionStartTimeFrom\x88\x01\x01\x126\n" +
	"\x15session_start_time_to\x18\a \x01(\tH\x06R\x12sessionStartTimeTo\x88\x01\x01\x12&\n" +
	"\ftitle_search\x18\b \x01(\tH\aR\vtitleSearch\x88\x01\x01\x12R\n" +
	"\asort_by\x18\t \x01(\tB4\xfaB1r/R\n" +
	"created_atR\n" +
	"updated_atR\x12session_start_time\xd0\x01\x01H\bR\x06sortBy\x88\x01\x01\x127\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\tB\x13\xfaB\x10r\x0eR\x03ascR\x04desc\xd0\x01\x01H\tR\tsortOrder\x88\x01\x01B\r\n" +
	"\v_page_tokenB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\t\n" +
	"\a_statusB\r\n" +
	"\v_visibilityB\x1a\n" +
	"\x18_session_start_time_fromB\x18\n" +
	"\x16_session_start_time_toB\x0f\n" +
	"\r_title_searchB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"\xce\x04\n" +
	"\x11PatchEventRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12'\n" +
	"\x05title\x18\x02 \x01(\tB\f\xfaB\tr\a\x10\x01\x18<\xd0\x01\x01H\x00R\x05title\x88\x01\x01\x12*\n" +
	"\asummary\x18\x03 \x01(\tB\v\xfaB\br\x06\x18\xa0\x01\xd0\x01\x01H\x01R\asummary\x88\x01\x01\x12A\n" +
	"\x06status\x18\x04 \x01(\tB$\xfaB!r\x1fR\x05draftR\tpublishedR\barchived\xd0\x01\x01H\x02R\x06status\x88\x01\x01\x12>\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tB\x19\xfaB\x16r\x14R\x06publicR\aprivate\xd0\x01\x01H\x03R\n" +
	"visibility\x88\x01\x01\x128\n" +
	"\x0fcover_image_url\x18\x06 \x01(\tB\v\xfaB\br\x06\xd0\x01\x01\x88\x01\x01H\x04R\rcoverImageUrl\x88\x01\x01\x120\n" +
	"\blocation\x18\a \x01(\v2\x0f.event.LocationH\x05R\blocation\x88\x01\x01\x12*\n" +
	"\bsessions\x18\b \x03(\v2\x0e.event.SessionR\bsessions\x12*\n" +
	"\x06detail\x18\t \x01(\v2\r.event.DetailH\x06R\x06detail\x88\x01\x01\x12(\n" +
	"\x03faq\x18\n" +
	" \x03(\v2\n" +
	".event.FAQB\n" +
	"\xfaB\a\x92\x01\x04\b\x00\x10\x14R\x03faqB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_summaryB\t\n" +
	"\a_statusB\r\n" +
	"\v_visibilityB\x12\n" +
	"\x10_cover_image_urlB\v\n" +
	"\t_locationB\t\n" +
	"\a_detail\"n\n" +
	"\x18UpdateEventStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x129\n" +
	"\x06status\x18\x02 \x01(\tB!\xfaB\x1er\x1cR\x05draftR\tpublishedR\barchivedR\x06status\"b\n" +
	"\x14DeleteSessionRequest\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aeventId\x12&\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tsessionId\"\xc9\x06\n" +
	"\x13SearchEventsRequest\x12\"\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tH\x00R\tpageToken\x88\x01\x01\x12 \n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01H\x01R\x04page\x88\x01\x01\x12+\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01H\x02R\bpageSize\x88\x01\x01\x12\x1e\n" +
	"\bbrand_id\x18\x04 \x01(\tH\x03R\abrandId\x88\x01\x01\x12&\n" +
	"\ftitle_search\x18\x05 \x01(\tH\x04R\vtitleSearch\x88\x01\x01\x12:\n" +
	"\x17session_start_time_from\x18\x06 \x01(\tH\x05R\x14sessionStartTimeFrom\x88\x01\x01\x126\n" +
	"\x15session_start_time_to\x18\a \x01(\tH\x06R\x12sessionStartTimeTo\x88\x01\x01\x12?\n" +
	"\flocation_lat\x18\b \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0H\aR\vlocationLat\x88\x01\x01\x12?\n" +
	"\flocation_lng\x18\t \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0H\bR\vlocationLng\x88\x01\x01\x125\n" +
	"\x0flocation_radius\x18\n" +
	" \x01(\x05B\a\xfaB\x04\x1a\x02(\x01H\tR\x0elocationRadius\x88\x01\x01\x12F\n" +
	"\asort_by\x18\v \x01(\tB(\xfaB%r#R\x12session_start_timeR\n" +
	"created_at\xd0\x01\x01H\n" +
	"R\x06sortBy\x88\x01\x01\x127\n" +
	"\n" +
	"sort_order\x18\f \x01(\tB\x13\xfaB\x10r\x0eR\x03ascR\x04desc\xd0\x01\x01H\vR\tsortOrder\x88\x01\x01B\r\n" +
	"\v_page_tokenB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\v\n" +
	"\t_brand_idB\x0f\n" +
	"\r_title_searchB\x1a\n" +
	"\x18_session_start_time_fromB\x18\n" +
	"\x16_session_start_time_toB\x0f\n" +
	"\r_location_latB\x0f\n" +
	"\r_location_lngB\x12\n" +
	"\x10_location_radiusB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"D\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"l\n" +
	"\x11EventListResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.event.PaginationR\n" +
	"pagination\"\x8d\x03\n" +
	"\n" +
	"Pagination\x12+\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tH\x00R\rnextPageToken\x88\x01\x01\x12+\n" +
	"\x0fprev_page_token\x18\x02 \x01(\tH\x01R\rprevPageToken\x88\x01\x01\x12\x1e\n" +
	"\bhas_next\x18\x03 \x01(\bH\x02R\ahasNext\x88\x01\x01\x12\x1e\n" +
	"\bhas_prev\x18\x04 \x01(\bH\x03R\ahasPrev\x88\x01\x01\x12$\n" +
	"\vtotal_count\x18\x05 \x01(\x05H\x04R\n" +
	"totalCount\x88\x01\x01\x12&\n" +
	"\fcurrent_page\x18\x06 \x01(\x05H\x05R\vcurrentPage\x88\x01\x01\x12$\n" +
	"\vtotal_pages\x18\a \x01(\x05H\x06R\n" +
	"totalPages\x88\x01\x01B\x12\n" +
	"\x10_next_page_tokenB\x12\n" +
	"\x10_prev_page_tokenB\v\n" +
	"\t_has_nextB\v\n" +
	"\t_has_prevB\x0e\n" +
	"\f_total_countB\x0f\n" +
	"\r_current_pageB\x0e\n" +
	"\f_total_pages\"P\n" +
	"\x13IsPublishedResponse\x12!\n" +
	"\fis_published\x18\x01 \x01(\bR\visPublished\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa1\x05\n" +
	"\fEventService\x12`\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/console/events\x12]\n" +
	"\fGetEventList\x12\x1a.event.GetEventListRequest\x1a\x18.event.EventListResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/console/events\x12?\n" +
	"\bGetEvent\x12\a.api.ID\x1a\f.event.Event\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/console/events/{id}\x12U\n" +
	"\n" +
	"PatchEvent\x12\x18.event.PatchEventRequest\x1a\f.event.Event\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/console/events/{id}\x12L\n" +
	"\vDeleteEvent\x12\a.api.ID\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/console/events/{id}\x12j\n" +
	"\x11UpdateEventStatus\x12\x1f.event.UpdateEventStatusRequest\x1a\f.event.Event\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/console/events/{id}/status\x12~\n" +
	"\rDeleteSession\x12\x1b.event.DeleteSessionRequest\x1a\x16.google.protobuf.Empty\"8\x82\xd3\xe4\x93\x022*0/console/events/{event_id}/sessions/{session_id}2\xfb\x01\n" +
	"\x12PublicEventService\x12U\n" +
	"\fSearchEvents\x12\x1a.event.SearchEventsRequest\x1a\x18.event.EventListResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/events\x127\n" +
	"\bGetEvent\x12\a.api.ID\x1a\f.event.Event\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/events/{id}\x12U\n" +
	"\vIsPublished\x12\a.api.ID\x1a\x1a.event.IsPublishedResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/events/{id}/is-publishedB\x11Z\x0fevent/api/eventb\x06proto3"

var (
	file_api_event_event_proto_rawDescOnce sync.Once
	file_api_event_event_proto_rawDescData []byte
)

func file_api_event_event_proto_rawDescGZIP() []byte {
	file_api_event_event_proto_rawDescOnce.Do(func() {
		file_api_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_event_event_proto_rawDesc), len(file_api_event_event_proto_rawDesc)))
	})
	return file_api_event_event_proto_rawDescData
}

var file_api_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_event_event_proto_goTypes = []any{
	(*Event)(nil),                    // 0: event.Event
	(*Location)(nil),                 // 1: event.Location
	(*GeoJSONPoint)(nil),             // 2: event.GeoJSONPoint
	(*Session)(nil),                  // 3: event.Session
	(*Detail)(nil),                   // 4: event.Detail
	(*FAQ)(nil),                      // 5: event.FAQ
	(*CreateEventRequest)(nil),       // 6: event.CreateEventRequest
	(*GetEventListRequest)(nil),      // 7: event.GetEventListRequest
	(*PatchEventRequest)(nil),        // 8: event.PatchEventRequest
	(*UpdateEventStatusRequest)(nil), // 9: event.UpdateEventStatusRequest
	(*DeleteSessionRequest)(nil),     // 10: event.DeleteSessionRequest
	(*SearchEventsRequest)(nil),      // 11: event.SearchEventsRequest
	(*CreateEventResponse)(nil),      // 12: event.CreateEventResponse
	(*EventListResponse)(nil),        // 13: event.EventListResponse
	(*Pagination)(nil),               // 14: event.Pagination
	(*IsPublishedResponse)(nil),      // 15: event.IsPublishedResponse
	(*api.ID)(nil),                   // 16: api.ID
	(*emptypb.Empty)(nil),            // 17: google.protobuf.Empty
}
var file_api_event_event_proto_depIdxs = []int32{
	1,  // 0: event.Event.location:type_name -> event.Location
	3,  // 1: event.Event.sessions:type_name -> event.Session
	4,  // 2: event.Event.detail:type_name -> event.Detail
	5,  // 3: event.Event.faq:type_name -> event.FAQ
	2,  // 4: event.Location.coordinates:type_name -> event.GeoJSONPoint
	1,  // 5: event.CreateEventRequest.location:type_name -> event.Location
	3,  // 6: event.CreateEventRequest.sessions:type_name -> event.Session
	4,  // 7: event.CreateEventRequest.detail:type_name -> event.Detail
	5,  // 8: event.CreateEventRequest.faq:type_name -> event.FAQ
	1,  // 9: event.PatchEventRequest.location:type_name -> event.Location
	3,  // 10: event.PatchEventRequest.sessions:type_name -> event.Session
	4,  // 11: event.PatchEventRequest.detail:type_name -> event.Detail
	5,  // 12: event.PatchEventRequest.faq:type_name -> event.FAQ
	0,  // 13: event.EventListResponse.events:type_name -> event.Event
	14, // 14: event.EventListResponse.pagination:type_name -> event.Pagination
	6,  // 15: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	7,  // 16: event.EventService.GetEventList:input_type -> event.GetEventListRequest
	16, // 17: event.EventService.GetEvent:input_type -> api.ID
	8,  // 18: event.EventService.PatchEvent:input_type -> event.PatchEventRequest
	16, // 19: event.EventService.DeleteEvent:input_type -> api.ID
	9,  // 20: event.EventService.UpdateEventStatus:input_type -> event.UpdateEventStatusRequest
	10, // 21: event.EventService.DeleteSession:input_type -> event.DeleteSessionRequest
	11, // 22: event.PublicEventService.SearchEvents:input_type -> event.SearchEventsRequest
	16, // 23: event.PublicEventService.GetEvent:input_type -> api.ID
	16, // 24: event.PublicEventService.IsPublished:input_type -> api.ID
	12, // 25: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	13, // 26: event.EventService.GetEventList:output_type -> event.EventListResponse
	0,  // 27: event.EventService.GetEvent:output_type -> event.Event
	0,  // 28: event.EventService.PatchEvent:output_type -> event.Event
	17, // 29: event.EventService.DeleteEvent:output_type -> google.protobuf.Empty
	0,  // 30: event.EventService.UpdateEventStatus:output_type -> event.Event
	17, // 31: event.EventService.DeleteSession:output_type -> google.protobuf.Empty
	13, // 32: event.PublicEventService.SearchEvents:output_type -> event.EventListResponse
	0,  // 33: event.PublicEventService.GetEvent:output_type -> event.Event
	15, // 34: event.PublicEventService.IsPublished:output_type -> event.IsPublishedResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_event_event_proto_init() }
func file_api_event_event_proto_init() {
	if File_api_event_event_proto != nil {
		return
	}
	file_api_event_event_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_event_event_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_event_event_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_event_event_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_event_event_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_event_event_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_event_event_proto_rawDesc), len(file_api_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_event_event_proto_goTypes,
		DependencyIndexes: file_api_event_event_proto_depIdxs,
		MessageInfos:      file_api_event_event_proto_msgTypes,
	}.Build()
	File_api_event_event_proto = out.File
	file_api_event_event_proto_goTypes = nil
	file_api_event_event_proto_depIdxs = nil
}
