// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/order/orders.proto

package order

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddOrderRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddOrderRequestMultiError, or nil if none found.
func (m *AddOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Payment

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AddOrderRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AddOrderRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AddOrderRequestValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Subtotal

	// no validation rules for Total

	// no validation rules for Form

	// no validation rules for Event

	if len(errors) > 0 {
		return AddOrderRequestMultiError(errors)
	}

	return nil
}

// AddOrderRequestMultiError is an error wrapping multiple validation errors
// returned by AddOrderRequest.ValidateAll() if the designated constraints
// aren't met.
type AddOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddOrderRequestMultiError) AllErrors() []error { return m }

// AddOrderRequestValidationError is the validation error returned by
// AddOrderRequest.Validate if the designated constraints aren't met.
type AddOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddOrderRequestValidationError) ErrorName() string { return "AddOrderRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddOrderRequestValidationError{}

// Validate checks the field values on IsEventHasOrdersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IsEventHasOrdersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsEventHasOrdersRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IsEventHasOrdersRequestMultiError, or nil if none found.
func (m *IsEventHasOrdersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IsEventHasOrdersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Event

	if len(errors) > 0 {
		return IsEventHasOrdersRequestMultiError(errors)
	}

	return nil
}

// IsEventHasOrdersRequestMultiError is an error wrapping multiple validation
// errors returned by IsEventHasOrdersRequest.ValidateAll() if the designated
// constraints aren't met.
type IsEventHasOrdersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsEventHasOrdersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsEventHasOrdersRequestMultiError) AllErrors() []error { return m }

// IsEventHasOrdersRequestValidationError is the validation error returned by
// IsEventHasOrdersRequest.Validate if the designated constraints aren't met.
type IsEventHasOrdersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsEventHasOrdersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsEventHasOrdersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsEventHasOrdersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsEventHasOrdersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsEventHasOrdersRequestValidationError) ErrorName() string {
	return "IsEventHasOrdersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IsEventHasOrdersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsEventHasOrdersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsEventHasOrdersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsEventHasOrdersRequestValidationError{}

// Validate checks the field values on AddOrderRequest_Item with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddOrderRequest_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddOrderRequest_Item with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddOrderRequest_ItemMultiError, or nil if none found.
func (m *AddOrderRequest_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *AddOrderRequest_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ticket

	// no validation rules for Quantity

	if len(errors) > 0 {
		return AddOrderRequest_ItemMultiError(errors)
	}

	return nil
}

// AddOrderRequest_ItemMultiError is an error wrapping multiple validation
// errors returned by AddOrderRequest_Item.ValidateAll() if the designated
// constraints aren't met.
type AddOrderRequest_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddOrderRequest_ItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddOrderRequest_ItemMultiError) AllErrors() []error { return m }

// AddOrderRequest_ItemValidationError is the validation error returned by
// AddOrderRequest_Item.Validate if the designated constraints aren't met.
type AddOrderRequest_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddOrderRequest_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddOrderRequest_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddOrderRequest_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddOrderRequest_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddOrderRequest_ItemValidationError) ErrorName() string {
	return "AddOrderRequest_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e AddOrderRequest_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddOrderRequest_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddOrderRequest_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddOrderRequest_ItemValidationError{}
