// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/order/orders.proto

package order

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	api "event/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrderRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Payment       string                  `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Items         []*AddOrderRequest_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      string                  `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                  `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Form          string                  `protobuf:"bytes,6,opt,name=form,proto3" json:"form,omitempty"`
	Event         string                  `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_api_order_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderRequest) GetPayment() string {
	if x != nil {
		return x.Payment
	}
	return ""
}

func (x *AddOrderRequest) GetItems() []*AddOrderRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddOrderRequest) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *AddOrderRequest) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *AddOrderRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *AddOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type IsEventHasOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEventHasOrdersRequest) Reset() {
	*x = IsEventHasOrdersRequest{}
	mi := &file_api_order_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEventHasOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEventHasOrdersRequest) ProtoMessage() {}

func (x *IsEventHasOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEventHasOrdersRequest.ProtoReflect.Descriptor instead.
func (*IsEventHasOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{1}
}

func (x *IsEventHasOrdersRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type AddOrderRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest_Item) Reset() {
	*x = AddOrderRequest_Item{}
	mi := &file_api_order_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest_Item) ProtoMessage() {}

func (x *AddOrderRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest_Item.ProtoReflect.Descriptor instead.
func (*AddOrderRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddOrderRequest_Item) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *AddOrderRequest_Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_api_order_orders_proto protoreflect.FileDescriptor

const file_api_order_orders_proto_rawDesc = "" +
	"\n" +
	"\x16api/order/orders.proto\x12\n" +
	"api.orders\x1a\x10api/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a'third_party/buf/validate/validate.proto\"\xc7\x02\n" +
	"\x0fAddOrderRequest\x12\"\n" +
	"\apayment\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\apayment\x12@\n" +
	"\x05items\x18\x03 \x03(\v2 .api.orders.AddOrderRequest.ItemB\b\xbaH\x05\x92\x01\x02\b\x01R\x05items\x12#\n" +
	"\bsubtotal\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bsubtotal\x12\x1d\n" +
	"\x05total\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05total\x12\x1b\n" +
	"\x04form\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04form\x12\x1e\n" +
	"\x05event\x18\a \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x1aM\n" +
	"\x04Item\x12 \n" +
	"\x06ticket\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x06ticket\x12#\n" +
	"\bquantity\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\bquantity\"9\n" +
	"\x17IsEventHasOrdersRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event2\xd9\x01\n" +
	"\x06Orders\x12Z\n" +
	"\bAddOrder\x12\x1b.api.orders.AddOrderRequest\x1a\r.api.Response\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/{event}/tickets\x12s\n" +
	"\x10IsEventHasOrders\x12#.api.orders.IsEventHasOrdersRequest\x1a\r.api.Response\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/events/{event}/orders/existB\x11Z\x0fevent/api/orderb\x06proto3"

var (
	file_api_order_orders_proto_rawDescOnce sync.Once
	file_api_order_orders_proto_rawDescData []byte
)

func file_api_order_orders_proto_rawDescGZIP() []byte {
	file_api_order_orders_proto_rawDescOnce.Do(func() {
		file_api_order_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_orders_proto_rawDesc), len(file_api_order_orders_proto_rawDesc)))
	})
	return file_api_order_orders_proto_rawDescData
}

var file_api_order_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_order_orders_proto_goTypes = []any{
	(*AddOrderRequest)(nil),         // 0: api.orders.AddOrderRequest
	(*IsEventHasOrdersRequest)(nil), // 1: api.orders.IsEventHasOrdersRequest
	(*AddOrderRequest_Item)(nil),    // 2: api.orders.AddOrderRequest.Item
	(*api.Response)(nil),            // 3: api.Response
}
var file_api_order_orders_proto_depIdxs = []int32{
	2, // 0: api.orders.AddOrderRequest.items:type_name -> api.orders.AddOrderRequest.Item
	0, // 1: api.orders.Orders.AddOrder:input_type -> api.orders.AddOrderRequest
	1, // 2: api.orders.Orders.IsEventHasOrders:input_type -> api.orders.IsEventHasOrdersRequest
	3, // 3: api.orders.Orders.AddOrder:output_type -> api.Response
	3, // 4: api.orders.Orders.IsEventHasOrders:output_type -> api.Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_order_orders_proto_init() }
func file_api_order_orders_proto_init() {
	if File_api_order_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_orders_proto_rawDesc), len(file_api_order_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_orders_proto_goTypes,
		DependencyIndexes: file_api_order_orders_proto_depIdxs,
		MessageInfos:      file_api_order_orders_proto_msgTypes,
	}.Build()
	File_api_order_orders_proto = out.File
	file_api_order_orders_proto_goTypes = nil
	file_api_order_orders_proto_depIdxs = nil
}
