// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/order/orders.proto

package order

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	api "event/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_UNKNOWN    OrderStatus = 0
	OrderStatus_PROCESSING OrderStatus = 1
	OrderStatus_COMPLETED  OrderStatus = 2
	OrderStatus_CANCELLED  OrderStatus = 3
	OrderStatus_REFUNDED   OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PROCESSING",
		2: "COMPLETED",
		3: "CANCELLED",
		4: "REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"UNKNOWN":    0,
		"PROCESSING": 1,
		"COMPLETED":  2,
		"CANCELLED":  3,
		"REFUNDED":   4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_order_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_order_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{0}
}

type AddOrderRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Payment       string                  `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Items         []*AddOrderRequest_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      string                  `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                  `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Form          string                  `protobuf:"bytes,6,opt,name=form,proto3" json:"form,omitempty"`
	Event         string                  `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_api_order_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderRequest) GetPayment() string {
	if x != nil {
		return x.Payment
	}
	return ""
}

func (x *AddOrderRequest) GetItems() []*AddOrderRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddOrderRequest) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *AddOrderRequest) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *AddOrderRequest) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *AddOrderRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type IsEventHasOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEventHasOrdersRequest) Reset() {
	*x = IsEventHasOrdersRequest{}
	mi := &file_api_order_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEventHasOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEventHasOrdersRequest) ProtoMessage() {}

func (x *IsEventHasOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEventHasOrdersRequest.ProtoReflect.Descriptor instead.
func (*IsEventHasOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{1}
}

func (x *IsEventHasOrdersRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type GetOrdersByEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByEventRequest) Reset() {
	*x = GetOrdersByEventRequest{}
	mi := &file_api_order_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByEventRequest) ProtoMessage() {}

func (x *GetOrdersByEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByEventRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByEventRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersByEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Data          []*GetOrdersResponse_GetOrdersOrder `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_api_order_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersResponse) GetData() []*GetOrdersResponse_GetOrdersOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOrdersBySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersBySessionRequest) Reset() {
	*x = GetOrdersBySessionRequest{}
	mi := &file_api_order_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersBySessionRequest) ProtoMessage() {}

func (x *GetOrdersBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersBySessionRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersBySessionRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersBySessionRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type ChangeOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=api.orders.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeOrderStatusRequest) Reset() {
	*x = ChangeOrderStatusRequest{}
	mi := &file_api_order_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOrderStatusRequest) ProtoMessage() {}

func (x *ChangeOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeOrderStatusRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ChangeOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

type AddOrderRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest_Item) Reset() {
	*x = AddOrderRequest_Item{}
	mi := &file_api_order_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest_Item) ProtoMessage() {}

func (x *AddOrderRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest_Item.ProtoReflect.Descriptor instead.
func (*AddOrderRequest_Item) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddOrderRequest_Item) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *AddOrderRequest_Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetOrdersResponse_GetOrdersOrder struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Id            string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payment       string                                   `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	Items         []*GetOrdersResponse_GetOrdersOrder_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      string                                   `protobuf:"bytes,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Total         string                                   `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	Event         string                                   `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	Status        string                                   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                                   `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	User          *api.User                                `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt     *timestamppb.Timestamp                   `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp                   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse_GetOrdersOrder) Reset() {
	*x = GetOrdersResponse_GetOrdersOrder{}
	mi := &file_api_order_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse_GetOrdersOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse_GetOrdersOrder) ProtoMessage() {}

func (x *GetOrdersResponse_GetOrdersOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse_GetOrdersOrder.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse_GetOrdersOrder) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetOrdersResponse_GetOrdersOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetPayment() string {
	if x != nil {
		return x.Payment
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetItems() []*GetOrdersResponse_GetOrdersOrder_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder) GetUser() *api.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOrdersResponse_GetOrdersOrder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetOrdersResponse_GetOrdersOrder_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) Reset() {
	*x = GetOrdersResponse_GetOrdersOrder_Item{}
	mi := &file_api_order_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse_GetOrdersOrder_Item) ProtoMessage() {}

func (x *GetOrdersResponse_GetOrdersOrder_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse_GetOrdersOrder_Item.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse_GetOrdersOrder_Item) Descriptor() ([]byte, []int) {
	return file_api_order_orders_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrdersResponse_GetOrdersOrder_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

var File_api_order_orders_proto protoreflect.FileDescriptor

const file_api_order_orders_proto_rawDesc = "" +
	"\n" +
	"\x16api/order/orders.proto\x12\n" +
	"api.orders\x1a\x10api/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a'third_party/buf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n" +
	"\x0fAddOrderRequest\x12\"\n" +
	"\apayment\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\apayment\x12@\n" +
	"\x05items\x18\x03 \x03(\v2 .api.orders.AddOrderRequest.ItemB\b\xbaH\x05\x92\x01\x02\b\x01R\x05items\x12#\n" +
	"\bsubtotal\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bsubtotal\x12\x1d\n" +
	"\x05total\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05total\x12\x1b\n" +
	"\x04form\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04form\x12\x1e\n" +
	"\x05event\x18\a \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\x1aM\n" +
	"\x04Item\x12 \n" +
	"\x06ticket\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x06ticket\x12#\n" +
	"\bquantity\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\bquantity\"9\n" +
	"\x17IsEventHasOrdersRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\"9\n" +
	"\x17GetOrdersByEventRequest\x12\x1e\n" +
	"\x05event\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05event\"\xd0\x04\n" +
	"\x11GetOrdersResponse\x12@\n" +
	"\x04data\x18\x01 \x03(\v2,.api.orders.GetOrdersResponse.GetOrdersOrderR\x04data\x1a\xf8\x03\n" +
	"\x0eGetOrdersOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayment\x18\x02 \x01(\tR\apayment\x12G\n" +
	"\x05items\x18\x03 \x03(\v21.api.orders.GetOrdersResponse.GetOrdersOrder.ItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\tR\bsubtotal\x12\x14\n" +
	"\x05total\x18\x05 \x01(\tR\x05total\x12\x14\n" +
	"\x05event\x18\a \x01(\tR\x05event\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1d\n" +
	"\x04user\x18\n" +
	" \x01(\v2\t.api.UserR\x04user\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aj\n" +
	"\x04Item\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\"?\n" +
	"\x19GetOrdersBySessionRequest\x12\"\n" +
	"\asession\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\asession\"u\n" +
	"\x18ChangeOrderStatusRequest\x12\x1e\n" +
	"\x05order\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\x18R\x05order\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.api.orders.OrderStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status*V\n" +
	"\vOrderStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\f\n" +
	"\bREFUNDED\x10\x042\xf5\x04\n" +
	"\x12OrdersAdminService\x12h\n" +
	"\bAddOrder\x12\x1b.api.orders.AddOrderRequest\x1a\r.api.Response\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/console/events/{event}/orders\x12\x82\x01\n" +
	"\x14IsEventHasOpenOrders\x12#.api.orders.IsEventHasOrdersRequest\x1a\r.api.Response\"6\x82\xd3\xe4\x93\x020\x12./api/v1/console/events/{event}/orders/has-open\x12u\n" +
	"\x10GetOrdersByEvent\x12#.api.orders.GetOrdersByEventRequest\x1a\r.api.Response\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/console/events/{event}/orders\x12}\n" +
	"\x12GetOrdersBySession\x12%.api.orders.GetOrdersBySessionRequest\x1a\r.api.Response\"1\x82\xd3\xe4\x93\x02+\x12)/api/v1/console/sessions/{session}/orders\x12z\n" +
	"\x11ChangeOrderStatus\x12$.api.orders.ChangeOrderStatusRequest\x1a\r.api.Response\"0\x82\xd3\xe4\x93\x02*:\x01*2%/api/v1/console/orders/{order}/statusB\x11Z\x0fevent/api/orderb\x06proto3"

var (
	file_api_order_orders_proto_rawDescOnce sync.Once
	file_api_order_orders_proto_rawDescData []byte
)

func file_api_order_orders_proto_rawDescGZIP() []byte {
	file_api_order_orders_proto_rawDescOnce.Do(func() {
		file_api_order_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_orders_proto_rawDesc), len(file_api_order_orders_proto_rawDesc)))
	})
	return file_api_order_orders_proto_rawDescData
}

var file_api_order_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_order_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_order_orders_proto_goTypes = []any{
	(OrderStatus)(0),                              // 0: api.orders.OrderStatus
	(*AddOrderRequest)(nil),                       // 1: api.orders.AddOrderRequest
	(*IsEventHasOrdersRequest)(nil),               // 2: api.orders.IsEventHasOrdersRequest
	(*GetOrdersByEventRequest)(nil),               // 3: api.orders.GetOrdersByEventRequest
	(*GetOrdersResponse)(nil),                     // 4: api.orders.GetOrdersResponse
	(*GetOrdersBySessionRequest)(nil),             // 5: api.orders.GetOrdersBySessionRequest
	(*ChangeOrderStatusRequest)(nil),              // 6: api.orders.ChangeOrderStatusRequest
	(*AddOrderRequest_Item)(nil),                  // 7: api.orders.AddOrderRequest.Item
	(*GetOrdersResponse_GetOrdersOrder)(nil),      // 8: api.orders.GetOrdersResponse.GetOrdersOrder
	(*GetOrdersResponse_GetOrdersOrder_Item)(nil), // 9: api.orders.GetOrdersResponse.GetOrdersOrder.Item
	(*api.User)(nil),                              // 10: api.User
	(*timestamppb.Timestamp)(nil),                 // 11: google.protobuf.Timestamp
	(*api.Response)(nil),                          // 12: api.Response
}
var file_api_order_orders_proto_depIdxs = []int32{
	7,  // 0: api.orders.AddOrderRequest.items:type_name -> api.orders.AddOrderRequest.Item
	8,  // 1: api.orders.GetOrdersResponse.data:type_name -> api.orders.GetOrdersResponse.GetOrdersOrder
	0,  // 2: api.orders.ChangeOrderStatusRequest.status:type_name -> api.orders.OrderStatus
	9,  // 3: api.orders.GetOrdersResponse.GetOrdersOrder.items:type_name -> api.orders.GetOrdersResponse.GetOrdersOrder.Item
	10, // 4: api.orders.GetOrdersResponse.GetOrdersOrder.user:type_name -> api.User
	11, // 5: api.orders.GetOrdersResponse.GetOrdersOrder.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: api.orders.GetOrdersResponse.GetOrdersOrder.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: api.orders.OrdersAdminService.AddOrder:input_type -> api.orders.AddOrderRequest
	2,  // 8: api.orders.OrdersAdminService.IsEventHasOpenOrders:input_type -> api.orders.IsEventHasOrdersRequest
	3,  // 9: api.orders.OrdersAdminService.GetOrdersByEvent:input_type -> api.orders.GetOrdersByEventRequest
	5,  // 10: api.orders.OrdersAdminService.GetOrdersBySession:input_type -> api.orders.GetOrdersBySessionRequest
	6,  // 11: api.orders.OrdersAdminService.ChangeOrderStatus:input_type -> api.orders.ChangeOrderStatusRequest
	12, // 12: api.orders.OrdersAdminService.AddOrder:output_type -> api.Response
	12, // 13: api.orders.OrdersAdminService.IsEventHasOpenOrders:output_type -> api.Response
	12, // 14: api.orders.OrdersAdminService.GetOrdersByEvent:output_type -> api.Response
	12, // 15: api.orders.OrdersAdminService.GetOrdersBySession:output_type -> api.Response
	12, // 16: api.orders.OrdersAdminService.ChangeOrderStatus:output_type -> api.Response
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_order_orders_proto_init() }
func file_api_order_orders_proto_init() {
	if File_api_order_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_orders_proto_rawDesc), len(file_api_order_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_orders_proto_goTypes,
		DependencyIndexes: file_api_order_orders_proto_depIdxs,
		EnumInfos:         file_api_order_orders_proto_enumTypes,
		MessageInfos:      file_api_order_orders_proto_msgTypes,
	}.Build()
	File_api_order_orders_proto = out.File
	file_api_order_orders_proto_goTypes = nil
	file_api_order_orders_proto_depIdxs = nil
}
