syntax = "proto3";

option go_package = "event/api/order";

package api.orders;

import "api/common.proto";
import "google/api/annotations.proto";
import "third_party/buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

service OrdersAdminService {
  rpc AddOrder (AddOrderRequest) returns (Response) {
    option (google.api.http) = {
      post: "/api/v1/console/events/{event}/orders"
      body: "*"
    };
  };

  rpc IsEventHasOpenOrders (IsEventHasOrdersRequest) returns (Response) {
    option (google.api.http) = {
      get: "/api/v1/console/events/{event}/orders/has-open"
    };
  }

  rpc GetOrdersByEvent (GetOrdersByEventRequest) returns (Response) {
    option (google.api.http) = {
      get: "/api/v1/console/events/{event}/orders"
    };
  }

  rpc GetOrdersBySession (GetOrdersBySessionRequest) returns (Response) {
    option (google.api.http) = {
      get: "/api/v1/console/sessions/{session}/orders"
    };
  }

  rpc ChangeOrderStatus (ChangeOrderStatusRequest) returns (Response) {
    option (google.api.http) = {
      //highlight-start
      patch: "/api/v1/console/orders/{order}/status"
      //highlight-end
      body: "*"
    };
  }
}


message AddOrderRequest {
  string payment =1 [(buf.validate.field).string.len = 24];
  message Item {
    string ticket = 1 [(buf.validate.field).string.len = 24] ;
    uint32 quantity = 2 [(buf.validate.field).uint32.gt = 0];
  }
  repeated Item items = 3 [(buf.validate.field).repeated = {min_items: 1}];
  string subtotal = 4 [(buf.validate.field).string.min_len = 1];
  string total = 5 [(buf.validate.field).string.min_len = 1];
  string form = 6 [(buf.validate.field).string.min_len = 1];
  string event = 7 [(buf.validate.field).string.len = 24] ;
}

message IsEventHasOrdersRequest {
  string event = 1 [(buf.validate.field).string.len = 24];
}

message GetOrdersByEventRequest {
  string event = 1 [(buf.validate.field).string.len = 24];
}



message GetOrdersResponse {
  message GetOrdersOrder {
    string id = 1;
    string payment =2;
    message Item {
      string ticket = 1;
      string session = 2;
      int64 quantity = 3;
      string price = 4;
    }
    repeated Item items = 3;
    string subtotal = 4;
    string total = 5;
    string event = 7;
    string status = 8;
    string note = 9;
    User user = 10;
    google.protobuf.Timestamp created_at = 11;
    google.protobuf.Timestamp updated_at = 12;
  }
  repeated GetOrdersOrder data = 1;
}

message GetOrdersBySessionRequest {
  string session = 1 [(buf.validate.field).string.len = 24];
}

message ChangeOrderStatusRequest {
  string order = 1 [(buf.validate.field).string.len = 24];
    OrderStatus status = 2 [(buf.validate.field).enum.defined_only = true];
}

enum OrderStatus {
  UNKNOWN = 0;
  PROCESSING = 1;
  COMPLETED = 2;
  CANCELLED = 3;
  REFUNDED = 4;
}