services:
  event-console:
    image: sjc.vultrcr.com/oosa/event:dev
    container_name: event-console
    restart: always
    volumes:
      - ${CONFIG_FILE}:/etc/config.yaml:ro
    command: ["console", "--config", "/etc/config.yaml"]
    environment:
      - SERVICE_NAME=partivo_event_console
    ports:
      - "192.168.1.123:9081:8081"
  event-public:
    image: sjc.vultrcr.com/oosa/event:dev
    container_name: event-public
    restart: always
    volumes:
      - ${CONFIG_FILE}:/etc/config.yaml:ro
    ports:
      - "192.168.1.123:9082:8081"
    command: ["public", "--config", "/etc/config.yaml"]
    environment:
      - SERVICE_NAME=partivo_event_public
networks:
  default:
    name: oosa-network
    external: true